export const REQUEST_ALLMONS_PENDING = 'REQUEST_ALLMONS_PENDING';
export const REQUEST_ALLMONS_SUCCESS = 'REQUEST_ALLMONS_SUCCESS';
export const REQUEST_ALLMONS_FAILED = 'REQUEST_ALLMONS_FAILED';
export const REQUEST_ONEMON_PENDING = 'REQUEST_ONEMON_PENDING';
export const REQUEST_ONEMON_SUCCESS = 'REQUEST_ONEMON_SUCCESS';
export const REQUEST_ONEMON_FAILED = 'REQUEST_ONEMON_FAILED';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';