const REQUEST_ALLMONS_PENDING = 'REQUEST_ALLMONS_PENDING';
const REQUEST_ALLMONS_SUCCESS = 'REQUEST_ALLMONS_SUCCESS';
const REQUEST_ALLMONS_FAILED = 'REQUEST_ALLMONS_FAILED';
const REQUEST_ONEMON_PENDING = 'REQUEST_ONEMON_PENDING';
const REQUEST_ONEMON_SUCCESS = 'REQUEST_ONEMON_SUCCESS';
const REQUEST_ONEMON_FAILED = 'REQUEST_ONEMON_FAILED';