const REQUEST_AllMONS_PENDING = 'REQUEST_AllMONS_PENDING';
const REQUEST_AllMONS_SUCCESS = 'REQUEST_AllMONS_SUCCESS';
const REQUEST_AllMONS_FAILED = 'REQUEST_AllMONS_FAILED';
const REQUEST_ONEMON_PENDING = 'REQUEST_ONEMON_PENDING';
const REQUEST_ONEMON_SUCCESS = 'REQUEST_ONEMON_SUCCESS';
const REQUEST_ONEMON_FAILED = 'REQUEST_ONEMON_FAILED';